apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpav1
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hpav1-web
  targetCPUUtilizationPercentage: 10
