apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
    - image: nginx:1.25.3
      name: nginx
      resources:
        limits:
          memory: 200Mi
          cpu: 100m
        requests:
          memory: 100Mi
          cpu: 100m
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: test-volume
  volumes:
    - name: test-volume
      hostPath:
        # directory location on host
        path: /data
        # this field is optional
        type: Directory
