apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpav2
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: metrics-example
  metrics:
  - type: Pods
    pods:
      metric:
        name: example_requests
      target:
        type: AverageValue
        averageValue: 20
