apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpav2
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: metrics-example
  targetCPUUtilizationPercentage: 10
